### ISSUE TITLE
Should we continue with LDAP?

### ISSUE THREAD

**Issue by luke-john** [plugorgau/ugmm#3]
Whilst LDAP made a lot of sense when UGMM was initially created I think it is worthwhile considering moving to a very lightweight db.

Some advantages of a lightweight db:
- decrease complexity of the project
- easier for people to setup development instances
- generally more community knowledge so more potential developers

**Comment by timwhite** [comment]
Some background. We moved away from libpam-somedb because it was difficult to keep working, and the packages had lots of bugs that constantly broke things. LDAP was chosen because it is somewhat of a standard, and works with more than just pam and our user management system. Ideally we can integrate lots of external systems with LDAP.

However, the big question that needs to be asked, **do we need to provide SSO for our members**? If we don't provide shell accounts anymore, LDAP is overkill. If we have a couple of servers we wish to maintain user accounts on for admins, use configuration management like salt, chef, puppet etc, to manage those users.

This would then greatly simplify 'ugmm' or whatever we wished to replace it with. It wouldn't take someone long with a modern framework (e.g. Symfony) to knock together a system for managing members, processing payments, updating details etc. Most of the hardwork has already been done for us in other packages/bundles that we can just include. Then we just write the little bits in between.

**Comment by luke-john** [comment]
closing this issue as stale, while cleaning up my old github issues
